variable "clientId" {}
variable "clientSecret" {}
variable "tenant" {}
variable "subId" {}
variable "location" {}
variable "backend_username" {}
variable "backend_password" {}
variable "client_ssh" {}
variable "nat_ssh" {}
variable "vnet_address_space" {}
variable "FE_Sub_Address" {}
variable "BE_Sub_Address" {}
variable "NAT_Address" {}
variable "domain_name" {}
variable "PublicIP_Id" {}
variable "DATABASE_URL" {}
variable "SECRET" {}
